"""
Report Generator Module
-----------------------
Exports chat conversations into a formatted Microsoft Word
document for documentation and reporting purposes.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.shared import Pt

# ============================================================
# CONFIGURATION
# ============================================================

LOGGER = logging.getLogger(__name__)

PROJECT_TITLE = "Smart Document Intelligence System"

# ============================================================
# REPORT EXPORT
# ============================================================


def export_chat(
    chat_history: list[dict[str, Any]],
    filename: str | Path,
) -> None:
    """
    Export chat history to a formatted DOCX report.

    Parameters
    ----------
    chat_history : list
        Conversation history.

    filename : str | Path
        Output DOCX file path.
    """

    if not chat_history:
        LOGGER.warning("No chat history available for export.")
        return

    filename = Path(filename)

    try:

        document = Document()

        # ----------------------------------------------------
        # Title
        # ----------------------------------------------------

        title = document.add_heading(
            PROJECT_TITLE,
            level=1,
        )

        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        subtitle = document.add_paragraph()

        subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        subtitle.add_run(
            "AI-Powered Document Question Answering\n"
        ).bold = True

        subtitle.add_run(
            f"Generated on: "
            f"{datetime.now().strftime('%d %B %Y, %I:%M %p')}"
        )

        document.add_paragraph()

        # ----------------------------------------------------
        # Chat History
        # ----------------------------------------------------

        document.add_heading(
            "Conversation History",
            level=2,
        )

        for index, message in enumerate(
            chat_history,
            start=1,
        ):

            role = message.get(
                "role",
                "Unknown",
            ).capitalize()

            heading = document.add_heading(
                f"{index}. {role}",
                level=3,
            )

            heading.style.font.size = Pt(12)

            paragraph = document.add_paragraph()

            paragraph.style.font.size = Pt(11)

            paragraph.add_run(
                message.get(
                    "content",
                    "",
                )
            )

            document.add_paragraph()

        # ----------------------------------------------------
        # Footer
        # ----------------------------------------------------

        document.add_page_break()

        footer = document.add_paragraph()

        footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

        footer.add_run(
            "End of Report"
        ).bold = True

        footer.add_run(
            "\nGenerated by Smart Document Intelligence System"
        )

        document.save(filename)

        LOGGER.info(
            "Report exported successfully: %s",
            filename,
        )

    except Exception:

        LOGGER.exception(
            "Failed to export report."
        )

        raise